In [ ]:
# Karl Lee
# 
# Isolated CMB regions and Non-CMB regions for given 3D MRI Images
# 


import scipy.io
import numpy as np
import os
import nibabel as nib
import matplotlib.pyplot as plt
import random
%matplotlib notebook


In [2]:
NCR_total = {}
# a dictionary to store all Non CMB Region


j = 0
file_path_img = os.path.join('SWI/img')
# image source path
file_path_label = os.path.join('SWI/label')
# label source path
list = os.listdir(file_path_img)

nNCMB = 20
# number of Non CMB Regions to isolate for each subject

print(list)
for file in list[0:10]:
    
    if file.split('.')[1] == 'nii':
        
        x_invalid = []
        y_invalid = []
        z_invalid = []
        # list of xyz indices to avoid when isolating non CMB regions
    
        j += 1
        print('Subject N%s'%j)
        #load .nii -> convert .nii to numpy array
        print('Reference File Image:', file)
        mri = np.asarray(nib.load(file_path_img +'/' + file).get_data())
        print('Reference File Image Shape:', mri.shape)
        # gets shape (x, y, z)

        fileLabelMatrix = file.split('.')[0] + '.mat'
        print('Reference File Label Matrix:',fileLabelMatrix)
        detection_mat = scipy.io.loadmat(file_path_label + '/' + fileLabelMatrix)
        print('Total Number of CMBs for N%s:' %j, len(detection_mat['cen']))
        print('Location of CMB Centroid:' %j, detection_mat['cen'][0])
        
        # Obtain indices that we don't want overlapping with each CMBs
        # ±16 from centroid. 
        
        for k in range(len(detection_mat['cen'])):
            
            x_invalid += [*range(detection_mat['cen'][k][0]-16,detection_mat['cen'][k][0]+16)]
            y_invalid += [*range(detection_mat['cen'][k][1]-16,detection_mat['cen'][k][1]+16)]
            z_invalid += [*range(detection_mat['cen'][k][2]-16,detection_mat['cen'][k][2]+16)]
            print('X Invalid Range for CMB %s:'%k, x_invalid, "Y Invalid Range for CMB %s:"%k, y_invalid, "Z Invalid Range for CMB %s:"%k, z_invalid)

        # extract nNCR for each subject

        print ("Total X Invalid Range:", x_invalid,"Total Y Invalid Range:", y_invalid, "Total Z Invalid Range:", z_invalid)
        # Non CMB Region
        NCR = []
        while len(NCR) < nNCMB:
            # random coordinate generation
            x_random = random.randint(8,mri.shape[0]-8)
            y_random = random.randint(8,mri.shape[1]-8)
            z_random = random.randint(8,mri.shape[2]-8)

            print("Random x,y,z for Non CMB Region:", x_random,y_random,z_random)

            proceed = 1

            for i in x_invalid:
                if x_random == i:
                    print('x_false')
                    proceed = 0
            for i in y_invalid:
                if y_random == i:
                    print('y_false')
                    proceed = 0
            for i in z_invalid:
                if z_random == i:
                    print('z_false')
                    proceed = 0

            if proceed == 1:
                print("proceeding")
                NCR.append(mri[x_random-8:x_random+8,y_random-8:y_random+8,z_random-8:z_random+8])

            print(len(NCR))
            
        print("%s non-CMB regions were isolated." %(len(NCR)), "Adding to the master dictionary.")
        NCR_total['N%s'%j] = NCR
    else:
        pass

print(nNCMB,"Non-CMB regions for each subject were isolated. Total Non-CMB regions extracted: %s" %(j*nNCMB))
  


['04.nii', '03.nii', '12.nii', '15.nii', '20.nii', '02.nii', '05.nii', '14.nii', '13.nii', '19.nii', '10.nii', '17.nii', '.ipynb_checkpoints', '06.nii', '01.nii', '08.nii', '16.nii', '11.nii', '18.nii', '09.nii', '07.nii']
Subject N1
Reference File Image: 04.nii
Reference File Image Shape: (512, 512, 150)
Reference File Label Matrix: 04.mat
Total Number of CMBs for N1: 1
[180 276  84]
X Invalid Range for CMB 0: [164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195] Y Invalid Range for CMB 0: [260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291] Z Invalid Range for CMB 0: [68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Total X Invalid Range: [164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 1

Reference File Image Shape: (512, 512, 150)
Reference File Label Matrix: 12.mat
Total Number of CMBs for N3: 1
[173 405  55]
X Invalid Range for CMB 0: [157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188] Y Invalid Range for CMB 0: [389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420] Z Invalid Range for CMB 0: [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70]
Total X Invalid Range: [157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188] Total Y Invalid Range: [389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 

Reference File Image Shape: (343, 409, 147)
Reference File Label Matrix: 20.mat
Total Number of CMBs for N5: 2
[171 197  45]
X Invalid Range for CMB 0: [155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186] Y Invalid Range for CMB 0: [181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212] Z Invalid Range for CMB 0: [29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
X Invalid Range for CMB 1: [155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126] 

Reference File Image Shape: (512, 512, 150)
Reference File Label Matrix: 05.mat
Total Number of CMBs for N7: 1
[204 256 115]
X Invalid Range for CMB 0: [188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219] Y Invalid Range for CMB 0: [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271] Z Invalid Range for CMB 0: [99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130]
Total X Invalid Range: [188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219] Total Y Invalid Range: [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,

Reference File Image Shape: (512, 512, 150)
Reference File Label Matrix: 13.mat
Total Number of CMBs for N9: 1
[150 270  95]
X Invalid Range for CMB 0: [134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165] Y Invalid Range for CMB 0: [254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285] Z Invalid Range for CMB 0: [79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110]
Total X Invalid Range: [134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165] Total Y Invalid Range: [254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278,

In [3]:
# 2nd part of extraction because of MARCC Memory 'Overload'?


NCR_total = {}


j = 10
file_path_img = os.path.join('SWI/img')
file_path_label = os.path.join('SWI/label')
list = os.listdir(file_path_img)

nNCMB = 20

print(list)
for file in list[10:]:
    
    if file.split('.')[1] == 'nii':
        
        x_invalid = []
        y_invalid = []
        z_invalid = []
    
        j += 1
        print('Subject N%s'%j)
        #load .nii -> convert .nii to numpy array
        print('Reference File Image:', file)
        mri = np.asarray(nib.load(file_path_img +'/' + file).get_data())
        print('Reference File Image Shape:', mri.shape)
        # x, y, z

        fileLabelMatrix = file.split('.')[0] + '.mat'
        print('Reference File Label Matrix:',fileLabelMatrix)
        detection_mat = scipy.io.loadmat(file_path_label + '/' + fileLabelMatrix)
        print('Total Number of CMBs for N%s:' %j, len(detection_mat['cen']))
        print(detection_mat['cen'][0])
        
        # Obtain indexes that we don't want overlapping with each CMBs
        
        for k in range(len(detection_mat['cen'])):
            
            x_invalid += [*range(detection_mat['cen'][k][0]-16,detection_mat['cen'][k][0]+16)]
            y_invalid += [*range(detection_mat['cen'][k][1]-16,detection_mat['cen'][k][1]+16)]
            z_invalid += [*range(detection_mat['cen'][k][2]-16,detection_mat['cen'][k][2]+16)]
            print('X Invalid Range for CMB %s:'%k, x_invalid, "Y Invalid Range for CMB %s:"%k, y_invalid, "Z Invalid Range for CMB %s:"%k, z_invalid)

        # extract nNCR for each subject

        print ("Total X Invalid Range:", x_invalid,"Total Y Invalid Range:", y_invalid, "Total Z Invalid Range:", z_invalid)
        # Non CMB Region
        NCR = []
        while len(NCR) < nNCMB:
            # random coordinate generation
            x_random = random.randint(8,mri.shape[0]-8)
            y_random = random.randint(8,mri.shape[1]-8)
            z_random = random.randint(8,mri.shape[2]-8)

            print("Random x,y,z for Non CMB Region:", x_random,y_random,z_random)

            proceed = 1

            for i in x_invalid:
                if x_random == i:
                    print('x_false')
                    proceed = 0
            for i in y_invalid:
                if y_random == i:
                    print('y_false')
                    proceed = 0
            for i in z_invalid:
                if z_random == i:
                    print('z_false')
                    proceed = 0

            if proceed == 1:
                print("proceeding")
                NCR.append(mri[x_random-8:x_random+8,y_random-8:y_random+8,z_random-8:z_random+8])

            print(len(NCR))
            
        print("%s non-CMB regions were isolated." %(len(NCR)), "Adding to the master dictionary.")
        NCR_total['N%s'%j] = NCR
    else:
        pass

print(nNCMB,"Non-CMB regions for each subject were isolated. Total Non-CMB regions extracted: %s" %(j*nNCMB))

['04.nii', '03.nii', '12.nii', '15.nii', '20.nii', '02.nii', '05.nii', '14.nii', '13.nii', '19.nii', '10.nii', '17.nii', '.ipynb_checkpoints', '06.nii', '01.nii', '08.nii', '16.nii', '11.nii', '18.nii', '09.nii', '07.nii']
Subject N11
Reference File Image: 10.nii
Reference File Image Shape: (512, 512, 150)
Reference File Label Matrix: 10.mat
Total Number of CMBs for N11: 8
[310 300  71]
X Invalid Range for CMB 0: [294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325] Y Invalid Range for CMB 0: [284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315] Z Invalid Range for CMB 0: [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86]
X Invalid Range for CMB 1: [294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 

Reference File Image Shape: (374, 397, 147)
Reference File Label Matrix: 17.mat
Total Number of CMBs for N12: 7
[264 218  66]
X Invalid Range for CMB 0: [248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279] Y Invalid Range for CMB 0: [202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233] Z Invalid Range for CMB 0: [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81]
X Invalid Range for CMB 1: [248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276,

Reference File Image Shape: (512, 512, 150)
Reference File Label Matrix: 06.mat
Total Number of CMBs for N13: 1
[184 272  74]
X Invalid Range for CMB 0: [168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199] Y Invalid Range for CMB 0: [256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287] Z Invalid Range for CMB 0: [58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]
Total X Invalid Range: [168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199] Total Y Invalid Range: [256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282,

Reference File Image Shape: (368, 416, 147)
Reference File Label Matrix: 16.mat
Total Number of CMBs for N16: 11
[188 196  39]
X Invalid Range for CMB 0: [172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203] Y Invalid Range for CMB 0: [180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211] Z Invalid Range for CMB 0: [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]
X Invalid Range for CMB 1: [172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224

Reference File Image Shape: (512, 512, 150)
Reference File Label Matrix: 11.mat
Total Number of CMBs for N17: 2
[279 267 108]
X Invalid Range for CMB 0: [263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294] Y Invalid Range for CMB 0: [251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282] Z Invalid Range for CMB 0: [92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123]
X Invalid Range for CMB 1: [263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 

Reference File Image Shape: (512, 512, 150)
Reference File Label Matrix: 09.mat
Total Number of CMBs for N19: 11
[318 246  70]
X Invalid Range for CMB 0: [302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333] Y Invalid Range for CMB 0: [230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261] Z Invalid Range for CMB 0: [54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85]
X Invalid Range for CMB 1: [302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322

Reference File Image Shape: (512, 512, 150)
Reference File Label Matrix: 07.mat
Total Number of CMBs for N20: 1
[163 282  57]
X Invalid Range for CMB 0: [147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178] Y Invalid Range for CMB 0: [266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297] Z Invalid Range for CMB 0: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]
Total X Invalid Range: [147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178] Total Y Invalid Range: [266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292,

In [4]:
# To export the dictionary
np.save('NonCMB2', NCR_total)